# Generated by Django 2.2.3 on 2019-10-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(default='Null', upload_to='audio_files/'),
            preserve_default=False,
        ),
    ]
